# Generated by Django 4.2 on 2023-06-18 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birthdate_user_currency_user_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('krw', 'USD'), ('krw', 'KRW')], default=datetime.datetime(2023, 6, 18, 11, 9, 19, 359577, tzinfo=datetime.timezone.utc), max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=datetime.datetime(2023, 6, 18, 11, 9, 23, 958501, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('kr', 'Korean')], default=datetime.datetime(2023, 6, 18, 11, 9, 32, 811097, tzinfo=datetime.timezone.utc), max_length=2),
            preserve_default=False,
        ),
    ]
