# Generated by Django 4.2 on 2023-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': '색깔',
            },
        ),
        migrations.CreateModel(
            name='Mind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '관념',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': '기타',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': '형태',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('제목', models.CharField(default='', max_length=100, null=True, verbose_name='제목')),
                ('desc', models.TextField(default='', max_length=300, null=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('filter', models.CharField(choices=[('wom', 'wom'), ('man', 'man'), ('new', 'new'), ('today', 'today')], default='', max_length=10, null=True)),
                ('color', models.ManyToManyField(blank=True, to='pictures.color')),
                ('mind', models.ManyToManyField(blank=True, related_name='mind', to='pictures.mind')),
                ('other', models.ManyToManyField(blank=True, to='pictures.other')),
                ('shape', models.ManyToManyField(blank=True, related_name='shape', to='pictures.shape')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
