# Generated by Django 4.2 on 2023-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100, null=True, verbose_name='제목')),
                ('desc', models.TextField(default='', max_length=300, null=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
