# Generated by Django 4.2 on 2023-04-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Picture',
        ),
    ]
