# Generated by Django 4.2 on 2023-04-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_rename_project_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='제목',
        ),
    ]
