# Generated by Django 4.2 on 2023-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_rename_title_picture_제목'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='filter',
            field=models.CharField(choices=[('wom', 'wom'), ('man', 'man'), ('new', 'new'), ('today', 'today')], default='', max_length=10, null=True),
        ),
    ]
