# Generated by Django 4.2 on 2023-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_picture_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Mind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Mind',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Other',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Shape',
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='color',
            field=models.ManyToManyField(blank=True, to='pictures.color'),
        ),
        migrations.AddField(
            model_name='picture',
            name='mind',
            field=models.ManyToManyField(blank=True, to='pictures.mind'),
        ),
        migrations.AddField(
            model_name='picture',
            name='other',
            field=models.ManyToManyField(blank=True, to='pictures.other'),
        ),
        migrations.AddField(
            model_name='picture',
            name='shape',
            field=models.ManyToManyField(blank=True, to='pictures.shape'),
        ),
    ]
