# Generated by Django 4.2 on 2023-05-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_color_mind_other_shape_picture_color_picture_mind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color'},
        ),
        migrations.AlterModelOptions(
            name='mind',
            options={'verbose_name': 'Mind'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': 'Other'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name': 'Shape'},
        ),
    ]
