# Generated by Django 4.2 on 2023-05-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_alter_color_options_alter_mind_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='mind',
            options={'verbose_name': 'Room Type'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': 'House Rule'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
