# Generated by Django 4.2 on 2023-05-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_alter_color_options_alter_mind_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '색깔'},
        ),
        migrations.AlterModelOptions(
            name='mind',
            options={'verbose_name': '관념'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': '기타'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'verbose_name_plural': '형태'},
        ),
    ]
