# Generated by Django 4.2 on 2023-05-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0008_alter_color_options_alter_mind_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='mind',
            field=models.ManyToManyField(blank=True, related_name='mind', to='pictures.mind'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='shape',
            field=models.ManyToManyField(blank=True, related_name='shape', to='pictures.shape'),
        ),
    ]
